add typescript section
mrPronin/edu-web pull request #2
Opened 2023-11-26 14:30 UTC by ProninNikita

2023-11-26 14:32 UTC, ProninNikita commented
review pls my repo

2023-12-03 10:12 UTC, mrPronin requested changes

2023-12-03 10:12 UTC, mrPronin commented on diagrams/03-vcs.iuml
> ++++ 02.03 etc
Please replace to 02.04

2023-12-03 10:22 UTC, mrPronin approved these changes

2023-12-03 10:27 UTC, merged